# Generated by Django 2.2.2 on 2019-06-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message',
                 models.CharField(help_text='Enter any message of maximum 256 characters length.', max_length=256)),
                ('is_strict_palindrome', models.BooleanField(editable=False,
                                                             help_text='True if message is a strict palindrome, else false. Considers all characters, not only letters.')),
                ('is_relaxed_palindrome', models.BooleanField(editable=False,
                                                              help_text='True if message is a relaxed palindrome, else false. Considers only alphanumerical characters, disregards punctuation, spaces and other special characters.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the message was created.')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='When the message was last modified.')),
            ],
        ),
    ]
