version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: lOsED7WAYBDBG5GP31ju
  web:
    image: palindrome
    environment:
      POSTGRES_PASSWORD: lOsED7WAYBDBG5GP31ju
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
    depends_on:
      - db